version: '3'
services:
  server:
    build: .
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    links:
        - mongodb
    depends_on:
        - mongodb
    environment:
      PORT: 8000
      WAIT_HOSTS: mongodb:27017
      WAIT_HOSTS_TIMEOUT: 120
      WAIT_BEFORE_HOSTS: 2
  mongodb:
    image: mongo
    container_name: "mongodb"
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017